/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAccessibilityRouteImport } from './routes/account.accessibility'
import { Route as AccountActivityRouteImport } from './routes/account.activity'
import { Route as AccountLanguageRouteImport } from './routes/account.language'
import { Route as AccountOffersRouteImport } from './routes/account.offers'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as AccountWatchlistRouteImport } from './routes/account.watchlist'
import { Route as MercadoIndexRouteImport } from './routes/mercado.index'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MercadoNftNftNumberRouteImport } from './routes/mercado.nft.$nftNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccessibilityRoute = AccountAccessibilityRouteImport.update({
  id: '/account/accessibility',
  path: '/account/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLanguageRoute = AccountLanguageRouteImport.update({
  id: '/account/language',
  path: '/account/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOffersRoute = AccountOffersRouteImport.update({
  id: '/account/offers',
  path: '/account/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/account/support',
  path: '/account/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/account/wallets',
  path: '/account/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWatchlistRoute = AccountWatchlistRouteImport.update({
  id: '/account/watchlist',
  path: '/account/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoIndexRoute = MercadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MercadoRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoNftNftNumberRoute = MercadoNftNftNumberRouteImport.update({
  id: '/nft/$nftNumber',
  path: '/nft/$nftNumber',
  getParentRoute: () => MercadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/register': typeof RegisterRoute
  '/account/accessibility': typeof AccountAccessibilityRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/account/watchlist': typeof AccountWatchlistRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/mercado/nft/$nftNumber': typeof MercadoNftNftNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/accessibility': typeof AccountAccessibilityRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/account/watchlist': typeof AccountWatchlistRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account': typeof AccountIndexRoute
  '/mercado': typeof MercadoIndexRoute
  '/mercado/nft/$nftNumber': typeof MercadoNftNftNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/register': typeof RegisterRoute
  '/account/accessibility': typeof AccountAccessibilityRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/offers': typeof AccountOffersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/account/watchlist': typeof AccountWatchlistRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/mercado/nft/$nftNumber': typeof MercadoNftNftNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/mercado'
    | '/register'
    | '/account/accessibility'
    | '/account/activity'
    | '/account/language'
    | '/account/offers'
    | '/account/profile'
    | '/account/support'
    | '/account/wallets'
    | '/account/watchlist'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account/'
    | '/mercado/'
    | '/mercado/nft/$nftNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/register'
    | '/account/accessibility'
    | '/account/activity'
    | '/account/language'
    | '/account/offers'
    | '/account/profile'
    | '/account/support'
    | '/account/wallets'
    | '/account/watchlist'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account'
    | '/mercado'
    | '/mercado/nft/$nftNumber'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/mercado'
    | '/register'
    | '/account/accessibility'
    | '/account/activity'
    | '/account/language'
    | '/account/offers'
    | '/account/profile'
    | '/account/support'
    | '/account/wallets'
    | '/account/watchlist'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account/'
    | '/mercado/'
    | '/mercado/nft/$nftNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AccountAccessibilityRoute: typeof AccountAccessibilityRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountLanguageRoute: typeof AccountLanguageRoute
  AccountOffersRoute: typeof AccountOffersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  AccountWatchlistRoute: typeof AccountWatchlistRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/accessibility': {
      id: '/account/accessibility'
      path: '/account/accessibility'
      fullPath: '/account/accessibility'
      preLoaderRoute: typeof AccountAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/language': {
      id: '/account/language'
      path: '/account/language'
      fullPath: '/account/language'
      preLoaderRoute: typeof AccountLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/offers': {
      id: '/account/offers'
      path: '/account/offers'
      fullPath: '/account/offers'
      preLoaderRoute: typeof AccountOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/support': {
      id: '/account/support'
      path: '/account/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/account/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/watchlist': {
      id: '/account/watchlist'
      path: '/account/watchlist'
      fullPath: '/account/watchlist'
      preLoaderRoute: typeof AccountWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/': {
      id: '/mercado/'
      path: '/'
      fullPath: '/mercado/'
      preLoaderRoute: typeof MercadoIndexRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/nft/$nftNumber': {
      id: '/mercado/nft/$nftNumber'
      path: '/nft/$nftNumber'
      fullPath: '/mercado/nft/$nftNumber'
      preLoaderRoute: typeof MercadoNftNftNumberRouteImport
      parentRoute: typeof MercadoRoute
    }
  }
}

interface MercadoRouteChildren {
  MercadoIndexRoute: typeof MercadoIndexRoute
  MercadoNftNftNumberRoute: typeof MercadoNftNftNumberRoute
}

const MercadoRouteChildren: MercadoRouteChildren = {
  MercadoIndexRoute: MercadoIndexRoute,
  MercadoNftNftNumberRoute: MercadoNftNftNumberRoute,
}

const MercadoRouteWithChildren =
  MercadoRoute._addFileChildren(MercadoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AccountAccessibilityRoute: AccountAccessibilityRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountLanguageRoute: AccountLanguageRoute,
  AccountOffersRoute: AccountOffersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  AccountWatchlistRoute: AccountWatchlistRoute,
  NftsNftIdRoute: NftsNftIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
