/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/account/wallets',
  path: '/account/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/mercado'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/mercado'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/mercado'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  RegisterRoute: typeof RegisterRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/account/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  RegisterRoute: RegisterRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  NftsNftIdRoute: NftsNftIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
